### ISSUE TITLE
Ignoring ssh_options

### ISSUE THREAD

**Issue by rtgibbons** [ovaistariq/mha-helper#25]
With the new rewrite it appears that the --ssh-options that are being based in are being ingored

https://github.com/ovaistariq/mha-helper/blob/23c144fc69c2d090475fc93f6afe14ef5675624e/mha_helper/ssh_helper.py#L40-L91

When looking at the library for paramiko api docs, it seems they don't even support it.

On a call to `masterha_check_repl` , we are using ssh_options to specify the path of the key, so SSH connections are failing with it comes to the failover script checks.

Here are the complete list of options being based in

```
--ssh_options='-o ServerAliveInterval=60 -o ServerAliveCountMax=20 -o StrictHostKeyChecking=no -o ConnectionAttempts=5 -o PasswordAuthentication=no -o BatchMode=yes -i /etc/masterha/.ssh/id_rsa'
```

**Comment by ovaistariq** [comment]
@rtgibbons mha-helper now supports parsing the system user's ssh-config file. For example, if mha-helper is running as root user then the config file /root/.ssh/config Is that something that could work for you?

**Comment by ovaistariq** [comment]
You can look at the Chef cookbook here to see how I am doing it:
https://supermarket.chef.io/cookbooks/mysql-mha

**Comment by rtgibbons** [comment]
That is how I'm doing it for now, but all this config information is already in my masterha cluster configuration, which is getting passed to the helper scripts. Just trying to reduce the redundant configurations.

**Comment by ovaistariq** [comment]
Let me think about how to implement it. I would most likely have to parse the options and pass the ones to paramiko which it accepts.

**Comment by ovaistariq** [comment]
@rtgibbons another issue I have discovered with the ssh options is that, MHA does not pass the additional SSH options when executing the failover helper script with the "status" command. An example invocation by MHA is as follows:
```
Mon Nov 23 06:51:42 2015 - [info] Checking master_ip_failover_script status:
Mon Nov 23 06:51:42 2015 - [info]   /usr/bin/master_ip_hard_failover_helper --command=status --ssh_user=mha --orig_master_host=some_host --orig_master_ip=192.168.10.2 --orig_master_port=3306 
```

So a status check cannot be completely performed by MHA helper if it does not know how to SSH into the machine when SSH key, for example, is in a non-default path. What do you suggest we do in that case?

**Comment by rtgibbons** [comment]
When I run `masterha_check_repl` I see `--ssh_options` passed into `/usr/bin/master_ip_hard_failover_helper`

ex

```
Wed Nov 25 14:28:10 2015 - [info] Checking replication health on mha1-db1..
Wed Nov 25 14:28:10 2015 - [info]  ok.
Wed Nov 25 14:28:10 2015 - [info] Checking master_ip_failover_script status:
Wed Nov 25 14:28:10 2015 - [info]   /usr/bin/master_ip_hard_failover_helper --command=status --ssh_user=mysql --orig_master_host=mha1-db2 --orig_master_ip=192.168.100.103 --orig_master_port=3306  --ssh_options='-o ServerAliveInterval=60 -o ServerAliveCountMax=20 -o StrictHostKeyChecking=no -o ConnectionAttempts=5 -o PasswordAuthentication=no -o BatchMode=yes -i /etc/masterha/.ssh/id_rsa'
```

**Comment by ovaistariq** [comment]
@rtgibbons I will take another look.

**Comment by ovaistariq** [comment]
@rtgibbons I am sorry for going silent here. I have an idea on how to implement a fix for this bug and I will start on it tomorrow.

**Comment by rtgibbons** [comment]
Awesome Thanks! I'll be sure and test this out during our next staging setup (don't have one scheduled at the moment)

**Comment by ovaistariq** [comment]
@rtgibbons thanks. I have also pushed out a new package https://packagecloud.io/twindb/main/packages/el/6/python-mha_helper-0.4.1-1.noarch.rpm
